input/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='input_index'),
    path('get_donor_list/', views.get_donor_list, name='get_donor_list'),
    path('get_donors/', views.view_get_donors, name='get_donors'),
    path('edit_businesses/', views.edit_businesses, name='edit_businesses'),
    path('add_businesses/', views.add_businesses, name='add_businesses'),
    path('edit_businesses/delete_businesses/', views.delete_businesses, name='edit_businesses_delete_businesses'),
    path('edit_businesses/get_businesses/', views.get_businesses, name='edit_businesses_get_businesses'),
    path('edit_businesses/update_businesses/', views.update_businesses, name='edit_businesses_update_businesses')
]

ssspdev/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

sunday_supper_donations/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
import debug_toolbar
from django.conf import settings
from django.urls import include, path

from input import views as input_views
from settings import views as settings_views
from users import views as users_views
from users.forms import UserLoginForm
import debug_toolbar
from django.conf import settings
from django.urls import include, path

urlpatterns = [
    path('', users_views.register, name="register"),
    path('input/', include('input.urls')),
    path('admin/', admin.site.urls, name="admin"),
    path('register/', users_views.register, name="register"),
    path('login/', auth_views.LoginView.as_view(template_name="users/login.html", authentication_form=UserLoginForm),
         name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name="users/logout.html"), name="logout"),
    # adjusted analytics url routing
    path('analytics/', include('analytics.urls')),
    path('maketoken/', users_views.registration_token, name='maketoken'),
    path('__debug__/', include(debug_toolbar.urls)),
    path('settings/',include('settings.urls')),
]

users/models.py
# Create your models here.
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

User._meta.get_field('email')._unique = True


class RegistrationToken(models.Model):
    token = models.CharField(max_length=128)
    date_created = models.DateField(auto_now_add=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    expiration_period = models.SmallIntegerField(default=5, validators=[MaxValueValidator(20), MinValueValidator(1)])

    def __str__(self):
        return "Token: {}".format(self.token)

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import RegistrationToken


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True, max_length=100)
    token = forms.CharField(required=True, disabled=False, max_length=50)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', "token"]

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        fields = self.visible_fields()
        for visible in fields:
            # Add class to each of the form elements
            visible.field.widget.attrs['class'] = 'form-control'

        self.fields["username"].widget.attrs.update({"placeholder": "Username"})
        self.fields["email"].widget.attrs.update({"placeholder": "Email"})
        self.fields["password1"].widget.attrs.update({"placeholder": "Password"})
        self.fields["password2"].widget.attrs.update({"placeholder": "Confirm Password"})
        self.fields["token"].widget.attrs.update({"placeholder": "Invitation Code"})


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
        self.fields["username"].widget.attrs.update({"placeholder": "Username"})
        self.fields["password"].widget.attrs.update({"placeholder": "Password"})


class RegistrationTokenForm(forms.ModelForm):
    class Meta:
        model = RegistrationToken
        fields = ['expiration_period']

    def __init__(self, *args, **kwargs):
        super(RegistrationTokenForm, self).__init__(*args, **kwargs)

users/views.py
import random
import string

from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User, Group
from django.db import IntegrityError
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse

from helpers import remove_html_tags
from .forms import UserRegisterForm, RegistrationTokenForm
from .helpers import validate_token
from settings.queries import update_user_role

TOKEN_OPTIONS = string.ascii_uppercase + string.ascii_lowercase + string.digits


def handle_post_req(request):
    form = UserRegisterForm(request.POST)

    if form.is_valid():

        token = remove_html_tags(form.cleaned_data.get('token', ''))

        token_error_msg = validate_token(token)
        if token_error_msg:
            messages.error(request, f"Please make sure registration token is valid, {token_error_msg}")
            print("Please make sure registration token is valid")

        else:
            """
            Handle case where email address already exists.
            TODO: This try/except block has a similar purpose with the else statement
            later on, but it's needed to prevent the page from crashing when the
            user tries to register with an email address that already exists in the db.
            """
            try:
                form.save()
            except IntegrityError as e:
                print(e)

                # TODO: implement more consistent error messages
                if 'email' in str(e):
                    messages.error(request,f"An account with the email address {request.POST['email']} already exists.")
                else:
                    messages.error(request, f"Please make sure all fields are correct {form.errors}")
                return redirect('register')

            # If an IntegrityError wasn't thrown, account creation was a huge success
            username = form.cleaned_data.get('username')
            # Add the new user to the default group
            try:
                user = User.objects.filter(email=request.POST['email']).values()[0]
                update_user_role(user['id'],"User")
                print(f"Created [{username}] in group [{default_group['name']}]")
            except Exception as e:
                print(e)
                print(f"Error: Created [{username}] in no group")
            messages.success(request, f'Account created for {username}!')
            print(f'Account created for {username}!')

    else:
        form_errors = form.errors
        if "password2" in form_errors:
            form_errors["password"] = form_errors.pop("password2")
        messages.error(request, f"Please make sure all fields are correct {form.errors}")
        print("Form is invalid")

    return redirect('register')


def handle_get_req(request):
    form = UserRegisterForm(initial={'token': request.GET.get('token', '')})
    return render(request, 'users/register.html', {'form': form})


def register(request):
    if request.user.is_authenticated:
        # Logged in user can't register
        return redirect("input_index")
    if request.method == 'POST':
        return handle_post_req(request)
    elif request.method == 'GET':
        return handle_get_req(request)
    else:
        return HttpResponse("What???")


@login_required
@permission_required('users.add_registrationtoken')
def registration_token(request):
    if request.method == 'POST':
        token = ''.join(random.choices(TOKEN_OPTIONS, k=20))
        form = RegistrationTokenForm(data=request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.creator = request.user
            form.token = token
            form.save()

            return render(request, 'users/create_token.html',
                          {'token': "%s%s%s" % (
                              request.build_absolute_uri('/')[:-1],
                              reverse('register'),
                              "?token=" + token)
                           })
        else:
            messages.error(request, f"Please make sure registration token is valid, {form.errors}")
            return render(request, 'users/create_token.html')
    elif request.method == 'GET':
        return render(request, 'users/create_token.html', {'form': RegistrationTokenForm()})
    else:
        HttpResponse("ERROR...")

users/templates/users/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
    <meta name="robots" content="noindex">

    <link rel="icon" type="img/png" href="/static/favicon.png">

    <title>Sunday Supper</title>

    {#    TODO: remove all unused imports #}
    {#    TODO: make all possible imports async and handle that using $(window).on('load', function() {CODE HERE} #}
    <!-- Bootstrap core CSS -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
            integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"
            integrity="sha512-qTXRIMyZIFb8iQcfjXWCO8+M5Tbc38Qi5WzdPOYZHIlZpzBHG3L3by84BBBOiRGiEb7KKtAOAs5qYdUiZiQNNQ=="
            crossorigin="anonymous"></script>
    <script src="https://www.chartjs.org/samples/latest/utils.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.3.1/jquery.maskedinput.min.js"></script>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    {#JQuery #}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'style/main.css' %}">


    {# Load Dompurify #}
    <script async src="https://cdnjs.cloudflare.com/ajax/libs/dompurify/2.2.6/purify.js"
            integrity="sha512-8R2upKpclvhu7Nl8wd2zyQjLInCrt93Ph+5E3F540qrnNtOKUcKEFY3Wvd6h8pum64O0pevDDhymefOxjFliOA=="
            crossorigin="anonymous"></script>

    <!-- Chart.js -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>


    <!-- Bootstrap Table Filters Documentation: https://bootstrap-table.com/docs/extensions/filter-control/ -->
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>

    {#Adds sheetjs  https://github.com/SheetJS/sheetjs#}
    <script src="https://unpkg.com/xlsx/dist/xlsx.full.min.js"></script>


    {#    TODO: replace with a CDN #}
    <link rel="stylesheet" type="text/css" href="https://getbootstrap.com/docs/5.0/assets/css/docs.css">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/export/bootstrap-table-export.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
          integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w=="
          crossorigin="anonymous"/>

</head>

<script>
    function clean_inputs() {
        document.querySelectorAll("input,textarea").forEach(e => e.value = DOMPurify.sanitize(e.value, {
            ALLOWED_TAGS: [],
            ALLOWED_ATTR: [],
            KEEP_TEXT: true,
            SAFE_FOR_TEMPLATES: true,
            FORBID_TAGS: ["\{\{", "\{\%"],
            ALLOW_DATA_ATTR: false,
        }));
    }
</script>


<body>
    <div class="container">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">

            <a class="navbar-brand" href="{% url 'input_index' %}">
                <img src="{% static "imgs/logo.png" %}" alt="logo" class="d-inline-block align-top">
                Sunday Supper
            </a>

            <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav mr-auto">
                    {% if user.is_authenticated %}

                        <!-- Input dropdown -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button"
                               data-bs-toggle="dropdown"
                               aria-expanded="false">Input</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item " href="{% url 'input_index' %}">Add Donation</a></li>
                                <li><a class="dropdown-item " href="{% url 'add_businesses' %}">Add Business</a></li>
                            </ul>
                        </li>

                        <!-- Analytics dropdown -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button"
                               data-bs-toggle="dropdown"
                               aria-expanded="false">Analytics</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item " href="{% url 'analytics_index' %}">View Charts</a></li>
                                <li><a class="dropdown-item " href="{% url 'analytics_rawdata' %}">View Tables</a></li>
                            </ul>
                        </li>

                        <!-- Audit Dropdown -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button"
                               data-bs-toggle="dropdown"
                               aria-expanded="false">Audit</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item " href="{% url 'edit_businesses' %}">Edit Business</a></li>
                                <li><a class="dropdown-item " href="{% url 'analytics_edit_donations' %}">Edit Donation</a></li>
                                <li><a class="dropdown-item " href="{% url 'analytics_edit_donors' %}">Edit Donor</a></li>
                            </ul>
                        </li>

                        <!-- Setting dropdown -->
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle text-white" id="navbarDropdownSettings" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">Settings</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownSettings">
                                <li><a class="dropdown-item" href="{% url 'change_password' %}">Change Password</a></li>
                                    {% if user.is_staff %}
                                        <li><a class="dropdown-item" href="{% url 'maketoken' %}">Create Registration Link</a></li>
                                        <li><a class="dropdown-item" href="{% url 'manage_registration_links' %}">Manage
                                            Registration Links</a></li>
                                        <li><a class="dropdown-item" href="{% url 'manage_roles' %}">Manage User Roles</a></li>
                                    {% endif %}
                                    {% if user.is_superuser %}
                                        <li><a class="dropdown-item" href="{% url 'admin:index' %}">Django Admin Page</a></li>
                                    {% endif %}
                                    <li><a class="dropdown-item" href="{% url 'help' %}">Help</a></li>
                            </ul>
                        </li>
                        {% else %}
                            <li class="nav-item active">
                                <a class="nav-link text-white" href="{% url 'login' %}">Log in</a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link text-white" href="{% url 'register' %}">Register</a>
                            </li>
                        {% endif %}
                </ul>
                
                <!-- Display username and Logout Link on far right -->
                {% if user.is_authenticated %}
                    <ul class="navbar-nav navbar-right">

                        <li class="nav-item active me-3">
                            <span class="navbar-text text-white"> Welcome, {{ user.username }}</span>
                        </li>

                        <li class="nav-item active me-5">
                            <a class="nav-link text-white" href="{% url 'logout' %}">Log out</a>
                        </li>
                    </ul>
                {% endif %}
            </div>
        </nav>
    </div>

<main role="main" class="container">
    {% block content %}


    {% endblock %}
</main>


<footer class="footer mt-auto py-3 bg-dark">
    <div class="container">
        {#      TODO: Add appropriate footer content #}
        <span class="text-white">© 2021 Copyright: Sunday Supper</span>
    </div>
</footer>

</body>
</html>

users/templates/users/create_token.html
{% extends 'users/base.html' %}

{% block content %}
    <div class="login-form">
        <form method="post" class="text-center" xmlns="http://www.w3.org/1999/html">
            <div class="form-group">
                {% csrf_token %}

                {% include 'users/msg.html' %}

                {% if form %}
                    <h3 class="text-dark mb-4 text-start">Create Registration Link</h3>
                    <hr>
                    <div class="input-group d-flex justify-content-start">
                        <label class="text-dark" for="expiration_period" style="padding-right: 10px;">Days to expire: </label>
                        <input class="form-control-lg text-dark" type="number" name="expiration_period" id="expiration_period" value="7" max="20" min="1">
                    </div>

                {% endif %}
                {% if token %}
                    <h2>Click Link To Copy</h2>
                    <hr>
                    <a id="generated_link" style="font-size: 18pt;" onclick="copyLink($(this))" onmouseout="outFunc()"

                       href="#">{{ token }}</a>

                {% endif %}
                <button type="submit" class="btn btn-primary btn-lg center-block mt-3 mb-5 w-25">Create</button>
            </div>
        </form>
    <div>



    <script>
        function copyLink(element) {
            var $temp = $("<input>");
            $("body").append($temp);
            $temp.val($(element).text()).select();
            document.execCommand("copy");
            $temp.remove();
        }

        function outFunc() {
            var tooltip = document.getElementById("myTooltip");
            tooltip.innerHTML = "Copy to clipboard";
        }
    </script>
{% endblock %}

users/templates/users/login.html
{% extends 'users/base.html' %}

{% block content %}

    {% include 'users/msg.html' %}

    <div class="login-form">
        <form action="" method="post">
            {% csrf_token %}
            <h2>Login</h2>
            <p>Please fill in this form to login!</p>
            <hr>

            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-user"></i></span>
                    {{ form.username }}
                </div>
            </div>

            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                    {{ form.password }}
                </div>
            </div>

            <div class="form-group ">
                <button type="submit" class="btn btn-primary btn-lg form-control">Login</button>
            </div>
        </form>
        <div class="text-center">Don't have an account? <a href="{% url "register" %}">Register</a></div>
    </div>
{% endblock %}

users/templates/users/msg.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'error' %}
            <div class="alert alert-danger">
                {{ message |safe }}
            </div>
        {% else %}
            <div class="alert alert-{{ message.tags }}">
                {{ message | safe }}
            </div>

        {% endif %}
    {% endfor %}
{% endif %}

users/templates/users/register.html
{% extends 'users/base.html' %}

{% block content %}

    {% include 'users/msg.html' %}

    <div class="signup-form">
        <form action="" method="post">
            {% csrf_token %}
            <h2>Sign Up</h2>
            <p>Please fill in this form to create an account!</p>
            <hr>

            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-user"></i></span>
                    {{ form.username }}
                </div>
            </div>

            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-paper-plane"></i></span>
                    {{ form.email }}
                </div>
            </div>

            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                    {{ form.password1 }}
                </div>
            </div>

            <div class="form-group">
                <div class="input-group">
				<span class="input-group-addon">
					<i class="fa fa-lock"></i>
					<i class="fa fa-check"></i>
				</span>
                    {{ form.password2 }}
                </div>
            </div>

            <div class="form-group">
                <div class="input-group">
				<span class="input-group-addon">
					<i class="fa fa-hand-paper-o"></i>
				</span>
                    {{ form.token }}
                </div>
            </div>

            <div class="form-group ">
                <button type="submit" class="btn btn-primary btn-lg form-control">Sign Up</button>
            </div>
        </form>
        <div class="text-center">Already have an account? <a href="{% url 'login' %}">Login here</a></div>
    </div>

    <script>
        if ($("#id_token").val() === "") {
            if (localStorage.getItem('registrationToken') != null)
                $("#id_token").val(localStorage.getItem('registrationToken'))
        } else {
            localStorage.setItem("registrationToken", $("#id_token").val());
        }
    </script>

{% endblock %}